Repository dani17b/web-productivio, pull requests merged in 2023-04, with the labels that each got.

#90 46 build ranking page
  src/App.tsx
  src/components/taskForm/TaskForm.tsx
  src/lib/axios/index.ts
  src/lib/axios/indexeddb/IndexedDB.ts
  src/modules/ranking/Ranking.tsx
  src/modules/ranking/actions.ts
  src/modules/ranking/ranking.scss
  src/modules/ranking/reducer.ts
  src/redux/reducers.ts
Labels: technical, functional

#93 lateral scrolling fixed
  src/modules/ranking/ranking.scss
Labels: bug

#102 merge conflicts resolved
  src/App.tsx
  src/components/feedBlock/FeedBlock.tsx
Labels: bug

#108 Navbar changed to webnavbar
  src/modules/userConfig/UserConfig.tsx
Labels: functional

#107 45 build circle page
  src/modules/circle/Circle.tsx
Labels: functional

#109 84 create roadmap parent component
  src/App.tsx
  src/components/roadmapParent/RoadmapParent.tsx
  src/components/roadmapParent/roadmapParent.scss
  src/modules/userProfile/UserProfile.tsx
  src/modules/userProfile/actions.ts
  src/modules/userProfile/reducer.ts
  src/modules/userProfile/userProfile.scss
  src/redux/reducers.ts
Labels: feature

#100 65 new team page
  src/App.tsx
  src/modules/newTeam/NewTeam.tsx
  src/modules/newTeam/actions.ts
  src/modules/newTeam/newTeam.scss
  src/modules/newTeam/reducer.ts
  src/redux/reducers.ts
Labels: feature

#112 fixed navbar bugs in testing
  package.json
  src/App.tsx
  src/components/webNavBar/WebNavBar.tsx
  src/modules/circle/Circle.tsx
  src/setupTests.js
Labels: bug

#118 bug styles fixed
  src/components/editTask/EditTask.tsx
  src/components/editTask/editTask.scss
  src/components/taskForm/TaskForm.tsx
  src/components/taskForm/taskForm.scss
Labels: bug

#114 Simple test added
  src/components/feedBlock/FeedBlock.test.tsx
  src/components/feedBlock/FeedBlock.tsx
Labels: technical, priority/low

#133 128 list components of a library in first column
  package.json
  productivio-components.json
  src/modules/editor/Editor.tsx
  src/modules/editor/components/componentList/ComponentList.tsx
  src/modules/editor/components/componentList/componentList.scss
Labels: functional

#134 127 create dragdrops styles manager
  src/components/propsEditor/StyleEditor.tsx
  src/components/propsEditor/TestComponent.tsx
  src/modules/editor/Editor.tsx
  src/modules/editor/components/infoPanel/InfoPanel.tsx
Labels: functional

#135 #126 Create dragdrop tab component
  package-lock.json
  package.json
  src/components/feedBlock/FeedBlock.tsx
  src/modules/editor/Editor.tsx
  src/modules/editor/ScreenSample.tsx
  src/modules/editor/components/tabComponent/TabComponent.tsx
  src/modules/editor/components/tabComponent/tabComponent.scss
Labels: feature

#140 127 create dragdrops property manager
  src/components/propsEditor/PropsEditor.tsx
  src/components/propsEditor/StyleEditor.tsx
  src/components/propsEditor/TestComponent.tsx
  src/modules/editor/Editor.tsx
  src/modules/editor/components/infoPanel/InfoPanel.tsx
Labels: functional

#132 122 create jsonreact parser
  src/index.js
  src/modules/notFound/NotFound.tsx
  src/utils/parser/JsonToTsx.js
  src/utils/parser/TsxToJson.ts
  src/utils/parser/examples/parsedComponentExample.json
Labels: functional

#145 json updated
  src/index.js
  src/utils/SetJsonStyle.ts
  src/utils/parser/TsxToJson.ts
  src/utils/parser/examples/parsedComponentExample.json
Labels: feature
