Repository dani17b/web-productivio, pull requests merged in 2023-05, with the labels that each got.

#150 130 get module from its route
  server/index.js
  server/utils/FileUtils.js
  src/modules/editor/Editor.tsx
  src/modules/editor/actions.ts
  src/modules/editor/reducer.ts
  src/redux/reducers.ts
Labels: feature, functional

#159 parse tsx to tagObj
  src/modules/editor/Editor.tsx
  src/modules/editor/actions.ts
  src/utils/parser/TsxToJson.ts
  src/utils/parser/examples/parsedComponentExample.json
Labels: feature

#161 152 update backend logic to support saving or updating more than one file at same time
  server/index.js
  src/index.js
  src/modules/editor/Editor.tsx
  src/utils/parser/JsonToScss.tsx
  src/utils/parser/TsxToJson.ts
Labels: functional
