Repository dani17b/web-productivio, pull requests merged in 2023-03, with the labels that each got.

#52 Component TaskForm created
  src/components/taskForm/TaskForm.tsx
  src/components/taskForm/taskForm.scss
Labels: functional, priority/medium

#58 feedBlock Created
  src/components/feedBlock/FeedBlock.tsx
  src/components/feedBlock/feedBlock.scss
Labels: feature, priority/low

#61 Swagger editor documentation revision
  docs/Swagger API Documentation.yaml
Labels: documentation

#68 62 align form page and expand buttons
  src/components/taskForm/TaskForm.tsx
  src/components/taskForm/taskForm.scss
  src/modules/newTask/NewTask.tsx
  src/modules/newTask/newTask.scss
Labels: functional, priority/medium

#77 69 add new task page
  src/components/taskForm/TaskForm.tsx
  src/components/taskForm/taskForm.scss
  src/lib/axios/index.ts
  src/modules/newTask/NewTask.tsx
  src/modules/newTask/actions.ts
  src/modules/newTask/newTask.scss
  src/modules/newTask/reducer.ts
  src/redux/reducers.ts
Labels: functional, priority/medium

#79 styling fixed
  src/modules/home/Home.tsx
  src/modules/home/home.scss
Labels: bug

#82 fixes in styles
  src/modules/home/home.scss
Labels: bug

#86 likedByMe implemented on web
  src/components/feedBlock/FeedBlock.tsx
  src/components/feedBlock/feedBlock.scss
  src/modules/home/Home.tsx
  src/modules/home/home.scss
Labels: feature, functional, priority/low
